/** Browse-all tiles: `key` must match `Song.genre` from the seed script. */
export const BROWSE_TILES: { key: string; label: string; className: string }[] = [
  { key: "new_hot", label: "New & Hot", className: "bg-gradient-to-br from-[#1e3264] to-[#5a7ab8]" },
  { key: "top_picks", label: "Top Picks", className: "bg-gradient-to-br from-[#7358ff] to-[#b49cff]" },
  { key: "throwback", label: "Throwback", className: "bg-gradient-to-br from-[#006450] to-[#1ed760]" },
  { key: "discover_weekly", label: "Discover Weekly", className: "bg-gradient-to-br from-[#283593] to-[#5c6bc0]" },
  { key: "release_radar", label: "Release Radar", className: "bg-gradient-to-br from-[#e91e63] to-[#f48fb1]" },
  { key: "Pop", label: "Pop", className: "bg-gradient-to-br from-[#8b44ac] to-[#c76fd8]" },
  { key: "Hip-Hop", label: "Hip-Hop", className: "bg-gradient-to-br from-[#e8115b] to-[#ff6b35]" },
  { key: "Rock", label: "Rock", className: "bg-gradient-to-br from-[#b71c1c] to-[#e53935]" },
  { key: "Latin", label: "Latin", className: "bg-gradient-to-br from-[#ff5722] to-[#ff9800]" },
  { key: "Dance/Electronic", label: "Dance/Electronic", className: "bg-gradient-to-br from-[#d500f9] to-[#ff4081]" },
  { key: "Indie", label: "Indie", className: "bg-gradient-to-br from-[#558b2f] to-[#9ccc65]" },
  { key: "R&B", label: "R&B", className: "bg-gradient-to-br from-[#006064] to-[#00838f]" },
  { key: "Country", label: "Country", className: "bg-gradient-to-br from-[#5d4037] to-[#8d6e63]" },
  { key: "Jazz", label: "Jazz", className: "bg-gradient-to-br from-[#0d47a1] to-[#1565c0]" },
  { key: "Classical", label: "Classical", className: "bg-gradient-to-br from-[#3e2723] to-[#6d4c41]" },
  { key: "Metal", label: "Metal", className: "bg-gradient-to-br from-[#1a237e] to-[#3949ab]" },
  { key: "Folk & Acoustic", label: "Folk & Acoustic", className: "bg-gradient-to-br from-[#b39ddb] to-[#e1bee7]" },
  { key: "Blues", label: "Blues", className: "bg-gradient-to-br from-[#37474f] to-[#546e7a]" },
  { key: "Soul", label: "Soul", className: "bg-gradient-to-br from-[#c2185b] to-[#f06292]" },
  { key: "Punk", label: "Punk", className: "bg-gradient-to-br from-[#0277bd] to-[#29b6f6]" },
  { key: "Reggae", label: "Reggae", className: "bg-gradient-to-br from-[#1b5e20] to-[#43a047]" },
  { key: "Ambient", label: "Ambient", className: "bg-gradient-to-br from-[#004d40] to-[#263238]" },
  { key: "K-Pop", label: "K-Pop", className: "bg-gradient-to-br from-[#ad1457] to-[#f48fb1]" },
  { key: "Podcasts", label: "Podcasts", className: "bg-gradient-to-br from-[#1b5e20] to-[#4caf50]" },
  { key: "Mood", label: "Mood", className: "bg-gradient-to-br from-[#455a64] to-[#78909c]" },
  { key: "Workout", label: "Workout", className: "bg-gradient-to-br from-[#c62828] to-[#ff7043]" },
  { key: "Focus", label: "Focus", className: "bg-gradient-to-br from-[#311b92] to-[#5e35b1]" },
  { key: "Chill", label: "Chill", className: "bg-gradient-to-br from-[#0277bd] to-[#4fc3f7]" },
  { key: "Sleep", label: "Sleep", className: "bg-gradient-to-br from-[#0d47a1] to-[#1e88e5]" },
];
